import random

top_bound = input("Type a number with in 100")

if top_bound.isdigit():
    top_bound = int(top_bound)

    if top_bound<0:
        print("Type a number a greater than 0")
        quit()

else:
    print("Type a number")
    quit()

random_numnber = random.randint(0,top_bound)

guess = input("Guess a number within 0 to top bound")
no_of_guesses = 1
while True:

    if guess.isdigit():
        guess = int(guess)
    else:
        print("Type a number")
        continue
    
    if (guess == random_numnber):
        print("your guess is correct which is equal to random number generated by backend", guess)
        print("number of guesses u needed is ", no_of_guesses)
        quit()
    elif (guess < random_numnber):
        no_of_guesses+=1
        guess = input("Choose a number greater than current")
    else:
        no_of_guesses+=1
        guess = input("Choose a number less than current")